// src/routes/TrueSkillCalculator.svelte
<script lang="ts">
	import { TrueSkill, Rating } from 'ts-trueskill';
	import { getDefaultTeam, type Team } from '../Teams';
	import { calculateRatings, matchQuality } from '../TrueSkill';
	import { getDefaultPlayer } from '../Players';

	let defaultMu = 25;
	let defaultSigma = 25 / 3;
	let betaValue = 25 / 6;
	let tauValue = betaValue / 2;
	let drawProbability = 0.1;

	let env = new TrueSkill(defaultMu, defaultSigma, betaValue, tauValue, drawProbability);

	export let teamCount = 2;

	export let currentTeams: Team[] = [
		{
			name: 'Team 1',
			players: [
				getDefaultPlayer(defaultMu, defaultSigma),
				getDefaultPlayer(defaultMu, defaultSigma)
			],
			rank: 1
		},
		{
			name: 'Team 2',
			players: [
				getDefaultPlayer(defaultMu, defaultSigma),
				getDefaultPlayer(defaultMu, defaultSigma)
			],
			rank: 2
		}
	];

	export let newTeams: Team[] = calculateRatings(env, currentTeams);
	export let quality = matchQuality(env, currentTeams);

	const incrementTeamCount = () => {
		if (teamCount < 50) {
			teamCount += 1;
			const newTeam = getDefaultTeam(defaultMu, defaultSigma, teamCount);
			currentTeams.push(newTeam);
			currentTeams = currentTeams;
			updateCalculations();
		}
	};

	const decreaseTeamCount = () => {
		if (teamCount > 2) {
			teamCount -= 1;
			currentTeams.pop();
			currentTeams = currentTeams;
			updateCalculations();
		}
	};

	const addPlayerToTeam = (teamIndex: number) => {
		if (currentTeams[teamIndex].players.length < 20) {
			currentTeams[teamIndex].players.push(getDefaultPlayer(defaultMu, defaultSigma));
			currentTeams = currentTeams;
			updateCalculations();
		}
	};

	const removePlayerFromTeam = (teamIndex: number) => {
		if (currentTeams[teamIndex].players.length > 1) {
			currentTeams[teamIndex].players.pop();
			currentTeams = currentTeams;
			updateCalculations();
		}
	};

	const updatePlayerInTeam = (
		teamIndex: number,
		playerIndex: number,
		newMu: number | undefined,
		newSigma: number | undefined
	) => {
		let mu = currentTeams[teamIndex].players[playerIndex].mu;
		let sigma = currentTeams[teamIndex].players[playerIndex].sigma;

		if (newMu !== undefined) {
			mu = newMu;
		}
		if (newSigma !== undefined) {
			sigma = newSigma;
		}

		currentTeams[teamIndex].players[playerIndex] = new Rating(mu, sigma);

		currentTeams = currentTeams;
		updateCalculations();
	};

	export const updateCalculations = function () {
		env = new TrueSkill(defaultMu, defaultSigma, betaValue, tauValue, drawProbability);
		newTeams = calculateRatings(env, currentTeams);
		quality = matchQuality(env, currentTeams);
	};
</script>

<h1>TrueSkill Online Calculator</h1>
<div class="box">
	<h2>Current Config:</h2>
	<p>Hover over the values to see the explanation.</p>
	<table>
		<tr>
			<td title="The default Value of Mu (μ) for new players."> Default Mu (μ):</td>
			<td>
				<input
					type="number"
					bind:value={defaultMu}
					on:input={() => {
						updateCalculations();
					}}
				/>
			</td>
		</tr>
		<tr>
			<td title="The default Value of Sigma (σ) for new players.">Default Sigma (σ):</td>
			<td>
				<input
					type="number"
					bind:value={defaultSigma}
					on:input={() => {
						updateCalculations();
					}}
				/>
			</td>
		</tr>
		<tr>
			<td
				title="The distance in rating points to guarantee about a 76% chance of winning for the higher rated player."
			>
				Beta (β):</td
			>
			<td>
				<input
					type="number"
					bind:value={betaValue}
					on:input={() => {
						updateCalculations();
					}}
				/>
			</td>
		</tr>
		<tr>
			<td title="The additive dynamics factor, the higher the value, the more dynamic the ratings.">
				Tau (τ):</td
			>
			<td>
				<input
					type="number"
					bind:value={tauValue}
					on:input={() => {
						updateCalculations();
					}}
				/>
			</td>
		</tr>
		<tr>
			<td title="The chance of a draw occurring in your game."> Draw Probability:</td>
			<td>
				<input
					type="number"
					bind:value={drawProbability}
					on:input={() => {
						updateCalculations();
					}}
				/>
			</td>
		</tr>
	</table>
</div>

<button on:click={() => incrementTeamCount()}> Add Team </button>
<button on:click={() => decreaseTeamCount()}> Remove Team </button>
<p><b>Starting Teams: ({teamCount})</b></p>
<table>
	<tr>
		<th>Team Name</th>
		<th>Rank</th>
		<th>Player Mu (μ) & Sigma (σ)</th>
	</tr>
	{#each currentTeams as team, i}
		<tr>
			<td>
				<input
					type="text"
					bind:value={team.name}
					on:input={() => {
						updateCalculations();
					}}
				/>
			</td>
			<td>
				<input
					type="number"
					bind:value={team.rank}
					on:input={() => {
						updateCalculations();
					}}
				/>
			</td>

			<td>
				{#each team.players as player, j}
					<input
						type="number"
						value={player.mu}
						on:input={(event) => {
							if (event.target instanceof HTMLInputElement) {
								updatePlayerInTeam(i, j, Number(event.target.valueAsNumber), undefined);
							}
						}}
					/>

					<input
						type="number"
						value={player.sigma}
						on:input={(event) => {
							if (event.target instanceof HTMLInputElement) {
								updatePlayerInTeam(i, j, undefined, Number(event.target.valueAsNumber));
							}
						}}
					/>
					<br />
				{/each}
			</td>
		</tr>
		<button on:click={() => addPlayerToTeam(i)}> Add Player </button>
		<button on:click={() => removePlayerFromTeam(i)}> Remove Player </button>
	{/each}
</table>
<br />
<div
	title="The match quality is the chance of a draw occurring in the given game. The higher the value, the closer the game will be."
>
	Match Quality: {quality}
</div>
<p><b>Resulting Teams: ({teamCount})</b></p>
<table>
	<tr>
		<th>Team Name</th>
		<th>Rank</th>
		<th>Player Mu (μ) & Sigma (σ)</th>
	</tr>
	{#each newTeams as team, i}
		<tr>
			<td>
				<input type="text" bind:value={team.name} readonly />
			</td>
			<td>
				<input type="text" bind:value={team.rank} readonly />
			</td>

			<td>
				{#each team.players as player, j}
					<input type="text" value={player.mu} readonly />

					<input type="text" value={player.sigma} readonly />
					<br />
				{/each}
			</td>
		</tr>
	{/each}
</table>

<style>
	.box {
		border: 1px solid black;
		padding: 10px;
		margin: 10px;
		background: #f2f2f2;
	}

	td {
		padding: 10px;
		background: #f2f2f2;
	}
</style>

// src/components/TrueSkillCalculator.vue
<script lang="ts">
import { copyMessage } from '@/helpers/copy';
import { TrueSkill } from 'ts-trueskill';
import { defineComponent } from 'vue';
import ConfigSidebar from '@/components/ConfigSidebar.vue';
import { getDefaultPlayer, type Player } from '@/helpers/players';
import { getDefaultTeam, getFirstTwoTeams, type Team } from '@/helpers/teams';
import { calculateRatings, matchQuality } from '@/helpers/trueskill';

export default defineComponent({
	name: 'TrueskillCalculator',
	data() {
		return {
			env: new TrueSkill() as TrueSkill,
			teamCount: 2,
			currentTeams: getFirstTwoTeams() as Team[],
			newTeams: [] as Team[],
			liveUpdates: true,
			quality: '',
			copyAllMessage: '📋 Copy All Teams As CSV',
			copyTeamMessage: '📋 Copy Team As CSV',
			copiedMessage: '✔️ Copied to Clipboard!'
		};
	},
	methods: {
		resetConfig(): void {
			this.env = new TrueSkill();
		},
		toggleLiveUpdates(): void {
			this.liveUpdates = !this.liveUpdates;
		},
		resetTeams(): void {
			this.teamCount = 2;
			this.currentTeams = getFirstTwoTeams();
		},
		refreshCalculations(forceRefresh: boolean = false): void {
			// Just a shortcut to calling both functions.
			if (this.liveUpdates || forceRefresh) {
				this.newTeams = calculateRatings(this.env as TrueSkill, this.currentTeams);
				this.quality = matchQuality(this.env as TrueSkill, this.currentTeams);
			}
		},
		incrementTeamCount(): void {
			// The limit is kind of arbitrary.
			if (this.teamCount < 256) {
				this.teamCount++;
				const newTeam = getDefaultTeam(this.teamCount, this.env.mu, this.env.sigma);
				this.currentTeams.push(newTeam);
			}
		},
		decrementTeamCount(): void {
			// Have to have at least 2 teams.
			if (this.teamCount > 2) {
				this.teamCount--;
				this.currentTeams.pop();
			}
		},
		addPlayerToTeam(team: Team, playerIndex: number): void {
			if (team.players.length < 256) {
				team.players.push(getDefaultPlayer(playerIndex, this.env.mu, this.env.sigma));
			}
		},
		removePlayerFromTeam(team: Team): void {
			// Have to have at least 1 player per team.
			if (team.players.length > 1) {
				team.players.pop();
			}
		},
		updatePlayerMuSigma(player: Player, newMu: number, newSigma: number): void {
			if (!newMu) {
				newMu = 0;
			}

			// The sigma value could be positive or negative, but just not 0.
			// The mu value can be whatever.
			if (newSigma) {
				player.rating = [newMu, newSigma];
			}
		},
		updatePlayerWeight(player: Player, newWeight: number): void {
			// The weight needs to be between 0 and 1.
			if (newWeight < 0 || !newWeight) {
				newWeight = 0;
			} else if (newWeight > 1) {
				newWeight = 1;
			}

			player.weight = newWeight;
		},
		updateTeamRanks(team: Team, newRank: number): void {
			// In reality, if Team A has a rank of 1, it does not matter if Team B's rank is 2 or 300.
			// Similarly, Team A's rank could also be -129, it just checks if it is lower/higher than the other Team.
			// But to keep it simple and to avoid confusion, we limit the ranks to be between 0 and the number of teams.
			if (newRank < 1 || !newRank) {
				newRank = 1;
			} else if (newRank > this.teamCount) {
				newRank = this.teamCount;
			}

			team.rank = newRank;
		},
		teamToCsv(team: Team): string {
			return team.players
				.map((player) => {
					return `${team.name},${team.rank},${player.name},${player.rating[0]},${player.rating[1]},${player.weight}`;
				})
				.join('\r');
		},
		allTeamsToCsv(teams: Team[]): string {
			return teams
				.map((team) => {
					return this.teamToCsv(team);
				})
				.join('\r');
		},
		copyAllTeamsButton(): void {
			copyMessage(this.allTeamsToCsv(this.newTeams));
			const oldMessage = this.copyAllMessage;
			this.copyAllMessage = this.copiedMessage;
			setTimeout(() => {
				this.copyAllMessage = oldMessage;
			}, 1000);
		},
		copyOneTeamButton(i: number): void {
			copyMessage(this.teamToCsv(this.newTeams[i]));
			const button = document.getElementsByClassName('copy-csv-button')[i + 1];
			button.innerHTML = this.copiedMessage;
			setTimeout(() => {
				button.innerHTML = this.copyTeamMessage;
			}, 1000);
		}
	},
	components: {
		ConfigSidebar
	},
	mounted() {
		this.refreshCalculations(false);
	},
	beforeUpdate() {
		this.refreshCalculations(false);
	}
});
</script>

<template>
	<div>
		<title>TrueSkill Calculator</title>
		<h1 class="text-5xl p-2">TrueSkill Calculator</h1>

		<ConfigSidebar
			:mu-value="env.mu"
			:sigma-value="env.sigma"
			:beta-value="env.beta"
			:tau-value="env.tau"
			:draw-probability="env.drawProbability"
			@mu-value="env.mu = $event"
			@sigma-value="env.sigma = $event"
			@beta-value="env.beta = $event"
			@tau-value="env.tau = $event"
			@draw-probability="env.drawProbability = $event"
			@reset-config="resetConfig"
			@toggle-live-updates="liveUpdates = !liveUpdates"
		/>

		<br />

		<table class="table-auto border-separate border-spacing-1">
			<tr>
				<td colspan="6">
					<b class="text-3xl">Starting Teams: ({{ teamCount }})</b>
					<button class="team-button shadow-green-500" @click="incrementTeamCount">
						Add New Team
					</button>

					<button class="team-button shadow-red-500" @click="decrementTeamCount">
						Remove Team
					</button>

					<button class="team-button shadow-blue-500" @click="resetTeams">
						Reset Teams
					</button>
				</td>
			</tr>

			<tr></tr>
			<tr></tr>

			<th class="text-2xl" title="The Name of the Team.">Team Name</th>
			<th
				class="text-2xl"
				title="The Rank, or the Placement of the Team. The lower the better."
			>
				Rank
			</th>
			<th class="text-2xl" title="The Names of the Players of this Team.">Players</th>
			<th class="text-2xl" title="The Mu (μ) Value of the Player.">Mu (μ)</th>
			<th class="text-2xl" title="The Sigma (σ) Value of the Player.">Sigma (σ)</th>
			<th
				class="text-2xl"
				title="How much of the Match the Player completed. 0 = Did not play at all, 1 = Played the whole Match."
			>
				Weight
			</th>
			<tr></tr>

			<tr class="odd:bg-gray-800" v-for="(team, j) in currentTeams" :key="j">
				<td>
					<input class="team-input" type="text" v-model="team.name" />
				</td>
				<td>
					<input
						class="team-input"
						type="number"
						min="1"
						:max="teamCount"
						v-model.number.lazy="team.rank"
						@input="
							updateTeamRanks(team, ($event.target as HTMLInputElement).valueAsNumber)
						"
					/>
				</td>
				<td>
					<tr v-for="(player, i) in team.players" :key="i">
						<input class="team-input" type="text" v-model="player.name" />
					</tr>
				</td>
				<td>
					<tr v-for="(player, i) in team.players" :key="i">
						<input
							class="team-input"
							type="number"
							step="0.1"
							v-model.number.lazy="player.rating[0]"
							@input="
								updatePlayerMuSigma(
									player,
									($event.target as HTMLInputElement).valueAsNumber,
									player.rating[1]
								)
							"
						/>
					</tr>
				</td>
				<td>
					<tr v-for="(player, i) in team.players" :key="i">
						<input
							class="team-input"
							type="number"
							step="0.01"
							v-model.number.lazy="player.rating[1]"
							@input="
								updatePlayerMuSigma(
									player,
									player.rating[0],
									($event.target as HTMLInputElement).valueAsNumber
								)
							"
						/>
					</tr>
				</td>
				<td>
					<tr v-for="(player, i) in team.players" :key="i">
						<input
							class="team-input"
							type="number"
							max="1"
							min="0"
							step="0.01"
							v-model.number.lazy="player.weight"
							@input="
								updatePlayerWeight(
									player,
									($event.target as HTMLInputElement).valueAsNumber
								)
							"
						/>
					</tr>
				</td>
				<button
					class="player-button shadow-green-500"
					@click="addPlayerToTeam(team, team.players.length + 1)"
				>
					Add Player
				</button>
				<button class="player-button shadow-red-500" @click="removePlayerFromTeam(team)">
					Remove Player
				</button>
			</tr>

			<tr v-show="!liveUpdates">
				<td>&nbsp;</td>
			</tr>

			<tr v-show="!liveUpdates">
				<td
					colspan="3"
					class="text-2xl text-center p-4 bg-gray-700 rounded border-white border hover:bg-gray-600 active:bg-gray-800 cursor-pointer shadow-md shadow-gray-500"
					@click="refreshCalculations(true)"
				>
					<button>Calculate New Ratings</button>
				</td>
			</tr>

			<tr>
				<td>&nbsp;</td>
			</tr>

			<td
				title="The match quality is the chance of a draw occurring in the given game. The higher the value, the closer the game will be."
				colspan="3"
				class="text-3xl text-center p-4 bg-gray-700 rounded border-white border"
			>
				Match Quality: {{ quality }}
			</td>

			<tr>
				<td>&nbsp;</td>
			</tr>

			<tr>
				<td colspan="6">
					<b class="text-3xl">Resulting Teams: ({{ newTeams.length }})</b>
					<button
						title="Copy All Teams as CSV"
						class="copy-csv-button ml-4 p-2 m-4"
						@click="copyAllTeamsButton"
					>
						{{ copyAllMessage }}
					</button>
				</td>
			</tr>

			<tr></tr>
			<tr></tr>

			<th class="text-2xl" title="The Name of the Team.">Team Name</th>
			<th
				class="text-2xl"
				title="The Rank, or the Placement of the Team. The lower the better."
			>
				Rank
			</th>
			<th class="text-2xl" title="The Names of the Players of this Team.">Players</th>
			<th class="text-2xl" title="The Mu (μ) Value of the Player.">Mu (μ)</th>
			<th class="text-2xl" title="The Sigma (σ) Value of the Player.">Sigma (σ)</th>
			<th
				class="text-2xl"
				title="How much of the Match the Player completed. 0 = Did not play at all, 1 = Played the whole Match."
			>
				Weight
			</th>

			<tr class="odd:bg-gray-800" v-for="(team, i) in newTeams" :key="i">
				<td>
					<div class="team-input">{{ team.name }}</div>
				</td>
				<td>
					<div class="team-input">{{ team.rank }}</div>
				</td>
				<td>
					<tr v-for="(player, i) in team.players" :key="i">
						<div class="team-input">{{ player.name }}</div>
					</tr>
				</td>
				<td>
					<tr v-for="(player, i) in team.players" :key="i">
						<div class="team-input">{{ player.rating[0] }}</div>
					</tr>
				</td>
				<td>
					<tr v-for="(player, i) in team.players" :key="i">
						<div class="team-input">{{ player.rating[1] }}</div>
					</tr>
				</td>
				<td>
					<tr v-for="(player, i) in team.players" :key="i">
						<div class="team-input">{{ player.weight }}</div>
					</tr>
				</td>
				<button
					title="Copy Team as CSV"
					class="copy-csv-button"
					@click="copyOneTeamButton(i)"
				>
					{{ copyTeamMessage }}
				</button>
			</tr>
		</table>
	</div>
</template>
